Feature/21 login screen
SandroGuerotto/PrettySecureCloud pull request #34
Opened 2022-04-14 16:46 UTC by bananasprout

implementation of loginscreen

2022-04-15 14:32 UTC, SandroGuerotto requested changes
Sobald mein PR #35 auf dem dev-branch ist, kannst du deinen Screen auf den neuesten Stand bringen.
Bei Fragen kannst du dich melden.
Prüfung noch ob du im Controller wirklich alle FXML Elemente benötigst.

2022-04-20 14:37 UTC, bananasprout commented
@SandroGuerotto Habe nicht herausgefunden, wie die Textfieldlängen "einfach" gleich lang werden, wie diese im Registerfenster. Werde wohl alles manuell setzen müssen...?!

2022-04-20 15:12 UTC, SandroGuerotto approved these changes

2022-04-20 15:13 UTC, SandroGuerotto approved these changes
LGM.
Du kannst die Änderungen reinziehen

2022-04-20 15:17 UTC, merged