27 key generator implementation
SandroGuerotto/PrettySecureCloud pull request #43
Opened 2022-04-23 10:58 UTC by Zuhlek

key generated implementiert:

1. generiert schlüssel im Auftrag vom cipher
2. generierte Schlüssel werden in einer Map<String, Key> gespeichert und zurückgegeben
3. die Schlüssel sollten später dem User angehängt werden
4. Unit test erstellt

2022-04-23 13:52 UTC, SandroGuerotto requested changes

2022-04-23 13:52 UTC, SandroGuerotto commented on src/main/java/ch/psc/datasource/JSONWriterReader.java
> +                    .registerTypeAdapter(SecretKeySpec.class, secretKeySerializer)
SecretKeySpec braucht es nicht.
Bitte umschreiben. Am besten eine TypeAdapterFactory von GSON verwenden und dann darin die Serialisierung/Deserialisierung einbauen.
Der JSONWriterReader muss so generisch wie möglich gehalten werden.

2022-04-23 13:52 UTC, SandroGuerotto commented on src/main/java/ch/psc/datasource/JSONWriterReader.java
> +                .registerTypeAdapter(SecretKeySpec.class, secretKeySerialization)
Ebenso mit TypeAdapterFactory arbeiten

2022-04-24 10:25 UTC, SandroGuerotto commented
Da #42 für die Persistenz der Daten zuständig ist, wäre es sinnvoller dort ein Mapping für den internen User und dem JSON-Objekt. Somit kann mit einer Map<String, Key> gearbeitet werden, aber sobald gespeichert wird, übernimmt der AuthService die Konvertierung.

2022-04-25 20:34 UTC, siebl commented on src/main/java/ch/psc/datasource/JSONWriterReader.java
> +                .registerTypeAdapter(SecretKeySpec.class, secretKeySerialization)
Mit ```SecretKeyTypeAdapterFactory``` umgesetzt

2022-04-26 07:03 UTC, SandroGuerotto approved these changes
Hatte eigentlich gedacht, dass die AdapterFactory eine Klasse liefert, welche das (De)Serialisieren übernimmt. Ist OK, da die AuthService Implementation die (De)Serialisieren übernimmt.

2022-04-27 17:10 UTC, merged